# Generated by Django 2.2.5 on 2019-09-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_user'),
        ('foods', '0002_food_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='restaurant',
            field=models.ForeignKey(
                default=4, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
            preserve_default=False,
        ),
    ]
